/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('antdv-next')['App']
    AButton: typeof import('antdv-next')['Button']
    ACheckbox: typeof import('antdv-next')['Checkbox']
    AColorPicker: typeof import('antdv-next')['ColorPicker']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADivider: typeof import('antdv-next')['Divider']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputNumber: typeof import('antdv-next')['InputNumber']
    AMenu: typeof import('antdv-next')['Menu']
    AMenuItem: typeof import('antdv-next')['MenuItem']
    AModal: typeof import('antdv-next')['Modal']
    APopover: typeof import('antdv-next')['Popover']
    AProgress: typeof import('antdv-next')['Progress']
    ASelect: typeof import('antdv-next')['Select']
    ASwitch: typeof import('antdv-next')['Switch']
    ATooltip: typeof import('antdv-next')['Tooltip']
  }
}

// For TSX support
declare global {
  const AApp: typeof import('antdv-next')['App']
  const AButton: typeof import('antdv-next')['Button']
  const ACheckbox: typeof import('antdv-next')['Checkbox']
  const AColorPicker: typeof import('antdv-next')['ColorPicker']
  const AConfigProvider: typeof import('antdv-next')['ConfigProvider']
  const ADivider: typeof import('antdv-next')['Divider']
  const ADropdown: typeof import('antdv-next')['Dropdown']
  const AForm: typeof import('antdv-next')['Form']
  const AFormItem: typeof import('antdv-next')['FormItem']
  const AInput: typeof import('antdv-next')['Input']
  const AInputNumber: typeof import('antdv-next')['InputNumber']
  const AMenu: typeof import('antdv-next')['Menu']
  const AMenuItem: typeof import('antdv-next')['MenuItem']
  const AModal: typeof import('antdv-next')['Modal']
  const APopover: typeof import('antdv-next')['Popover']
  const AProgress: typeof import('antdv-next')['Progress']
  const ASelect: typeof import('antdv-next')['Select']
  const ASwitch: typeof import('antdv-next')['Switch']
  const ATooltip: typeof import('antdv-next')['Tooltip']
}